### ISSUE TITLE
Vertical tabs have too little contrast with background

### ISSUE THREAD

**Issue by TheRealGLH** [dracula/firefox#13]
Which in turn means it's hard to see which tab is selected at a quick glance. If the sidebar is expanded, there's at least a button next to it but some more visual clarity would be ideal.

This is through the native, experimental implementation that can be enabled in about:config starting with Firefox 129:

![image](https://github.com/user-attachments/assets/f2c3fe16-2bcb-44c4-997d-749dc15e9058)

Compared with regular horizontal tabs:

![image](https://github.com/user-attachments/assets/aec82754-5fdc-40ba-9d06-6a7058ac0168)

Version info:
![image](https://github.com/user-attachments/assets/c3971b5c-2c5d-4829-9a11-38218148fac7)

**Comment by TheRealGLH** [comment]
I should have specified that this is about the browser theme extension version, not the userChrome theme.

**Comment by RaphGL** [comment]
Oh, so it's my version? I thought it was the userChrome one because you mentioned about:config lol, my bad.

I've went and enabled vertical bars and tried to spot where the issue is. I've managed to fix it. If you downloaded the theme from the Firefox Addons store then you should be getting the fix after firefox approves the changes
