### ISSUE TITLE
Toolbar colour incorrect

### ISSUE THREAD

**Issue by hudsonm62** [dracula/firefox#14]
Looks like after yesterdays commit (0a0f6e8), it broke the toolbar colour and now the whole theme looks wacky.

![image](https://github.com/user-attachments/assets/46e3ce4b-e531-4cd6-ad22-36f3fdafd50f)

## Vs Screenshot:

![image](https://github.com/user-attachments/assets/2653d472-5f82-4867-83ea-fcf30cd537b2)

Edit: using Firefox Addon version
![image](https://github.com/user-attachments/assets/e2c248c1-9432-4e26-822b-e1d8a1631946)

**Comment by RaphGL** [comment]
oops. I'll take a look lol

**Comment by RaphGL** [comment]
I've fixed this, but sadly the theme won't be the exact same as before, since firefox doesn't give us a way to theme the vertical and horizontal tab modes separately it seems.

The compromise I found is not ugly, but it might not be what people originally signed up for.
I might consider adding a "Dracula Classic" that doesn't support vertical tabs if people want prefer the old style better.

**Comment by shervinsafineh** [comment]
I tested the new version on Firefox Dev Edition and it doesn't look as good as before so I'd say that classic version consideration would at least have my +1 since I don't use vertical tabs and probably many other people don't either. For now, it's back to 1.10.0 for me. Thanks for your efforts regardless.

**Comment by RaphGL** [comment]
I've submitted the classic version to the addon store. it's awaiting approval
